### ISSUE TITLE
Enabling edge to edge mode

### ISSUE THREAD

**Issue by mertyldrr** [capacitor-community/safe-area#13]
First of all, thanks for the plugin @tafelnl  🙌 

This is not an issue about the plugin, rather consulting for opinions.

I am using setOverlaysWebView from `@capacitor/status-bar` to enable edge-to-edge mode, in addition to that, I am using your safe-area plugin to apply safe-area-insets. Is there a better way to do this?

**Comment by tafelnl** [comment]
If you're only using `setOverlaysWebView`, you don't need `@capacitor/status-bar` at all with this plugin. As this plugin already provides you with the needed utilities to enable edge-to-edge. Even more so, it allows you to set the colors of the system bars. So - though I have limited context of your specific situation of course - I would say you can simply remove the `@capacitor/status-bar` and use this plugin only

**Comment by mertyldrr** [comment]
Actually, I initially tried to remove `@capacitor/status-bar` completely but edge-to-edge is somehow not active when I only use this plugin (Google Pixel 6a - Android 14). This is config I am using in capacitor.config.ts:

```
    SafeArea: {
      enabled: true,
      customColorsForSystemBars: true,
      offset: 0,
    },
```

Also after app initialisation I execute this which updates navigation bar color correctly:

```
    SafeArea.enable({
      config: {
        navigationBarColor: color.hex
      }
    });
```

I am using `6.0.0-alpha.3`

**Comment by tafelnl** [comment]
Every time you call `.enable` you should provide it with all the options of which you don't want the default value. It won't remember any previous values you provided. Also you probably want to set `statusBarColor` and `navigationBarColor` to some transparent color. Otherwise you still won't be able to see the content beneath it of course. Without a reproduction it's very hard to give you any more information than what is already provided in the docs

**Comment by mertyldrr** [comment]
I thought it was transparent by default and would be edge-to-edge without specifying it explicitly 😅. using `statusBarColor: '#00000000'` fixed it, thank you.
